ALTER TABLE INGRESO_GIMNASIO ADD CONSTRAINT CLIENTE_fk FOREIGN KEY (CLI_CED_CLIENTE)
REFERENCES CLIENTE (CLI_CED) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE MANTENIMIENTO ADD CONSTRAINT MAQUINA_fk FOREIGN KEY (MAQ_COD_MAQUINA)
REFERENCES MAQUINA (MAQ_COD) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE MANTENIMIENTO ADD CONSTRAINT EMPRESA_DE_MANTENIMIENTO_fk FOREIGN KEY (EMPRESA_COD_EMPRESA_DE_MANTENIMIENTO)
REFERENCES EMPRESA_DE_MANTENIMIENTO (EMPRESA_COD) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE PERSONAL ADD CONSTRAINT TIPO_CARGO_fk FOREIGN KEY (TIPO_ID_TIPO_CARGO)
REFERENCES TIPO_CARGO (TIPO_ID) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CLIENTE ADD CONSTRAINT TIPO_CLIENTE_fk FOREIGN KEY (TIPO_ID_TIPO_CLIENTE)
REFERENCES TIPO_CLIENTE (TIPO_ID) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CLIENTE ADD CONSTRAINT RUTINA_fk FOREIGN KEY (RUTI_CODE_RUTINA)
REFERENCES RUTINA (RUTI_CODE) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE FACTURA ADD CONSTRAINT PERSONAL_fk FOREIGN KEY (PER_CODE_PERSONAL)
REFERENCES PERSONAL (PER_CODE) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE INGRESO_GIMNASIO ADD CONSTRAINT TIPO_PLAN_fk FOREIGN KEY (PLAN_ID_TIPO_PLAN)
REFERENCES TIPO_PLAN (PLAN_ID) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT CLIENTE_fk FOREIGN KEY (CLI_CED_CLIENTE)
REFERENCES CLIENTE (CLI_CED) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT PRODUCTO_ADICIONAL_fk FOREIGN KEY (PRO_ADI_COD_PRODUCTO_ADICIONAL)
REFERENCES PRODUCTO_ADICIONAL (PRO_ADI_COD) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FACTURA_fk FOREIGN KEY (FACT_NUM_FACTURA)
REFERENCES FACTURA (FACT_NUM) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE INGRESO_GIMNASIO ADD CONSTRAINT SECCION_fk FOREIGN KEY (SEC_CODI_SECCION)
REFERENCES SECCION (SEC_CODI) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE USO_MAQUINA ADD CONSTRAINT MAQUINA_fk FOREIGN KEY (MAQ_COD_MAQUINA)
REFERENCES MAQUINA (MAQ_COD) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE USO_MAQUINA ADD CONSTRAINT CLIENTE_fk FOREIGN KEY (CLI_CED_CLIENTE)
REFERENCES CLIENTE (CLI_CED) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE RUTINA_ESTABLECIDA ADD CONSTRAINT RUTINA_fk FOREIGN KEY (RUTI_CODE_RUTINA)
REFERENCES RUTINA (RUTI_CODE) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE RUTINA_ESTABLECIDA ADD CONSTRAINT PERSONAL_fk FOREIGN KEY (PER_CODE_PERSONAL)
REFERENCES PERSONAL (PER_CODE) MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
