CREATE TABLE TIPO_CARGO (
	TIPO_ID smallint NOT NULL,
	TIPO_DETALLE varchar(30),
	CONSTRAINT TIPO_CARGO_pk PRIMARY KEY (TIPO_ID)
);

CREATE TABLE CLIENTE (
	CLI_CED integer NOT NULL,
	CLI_NOMBRE varchar(30),
	CLI_APELLIDO varchar(30),
	CLI_NACIMIENTO date,
	CLI_CORRE varchar(30),
	CLI_TIPO_SANGRE varchar(5),
	CLI_CELULAR integer,
	CLI_CEL_EMERG integer,
	TIPO_ID_TIPO_CLIENTE smallint NOT NULL,
	RUTI_CODE_RUTINA smallint NOT NULL,
	CONSTRAINT CLIENTE_pk PRIMARY KEY (CLI_CED)
);

CREATE TABLE PERSONAL (
	PER_CODE integer NOT NULL,
	PER_NOMBRE varchar(30),
	PER_APELLIDO varchar(30),
	PER_CORREO varchar(40),
	PER_CELULAR integer,
	PER_ENTRADA timestamp,
	PER_SALIDA timestamp,
	TIPO_ID_TIPO_CARGO smallint NOT NULL,
	CONSTRAINT PERSONAL_pk PRIMARY KEY (PER_CODE)
);

CREATE TABLE MAQUINA (
	MAQ_COD smallint NOT NULL,
	MAQ_NOMBRE varchar(30),
	MAQ_DESCRIPCION varchar(50),
	MAQ_FEC_COMPRA date,
	MAQ_EJERCICIO varchar(40),
	CONSTRAINT MAQUINA_pk PRIMARY KEY (MAQ_COD)
);

CREATE TABLE MANTENIMIENTO (
	MANT_COD smallint NOT NULL,
	MANT_FECHA date,
	MAQ_COD_MAQUINA smallint NOT NULL,
	EMPRESA_COD_EMPRESA_DE_MANTENIMIENTO smallint NOT NULL,
	CONSTRAINT MANTENIMIENTO_pk PRIMARY KEY (MANT_COD)
);

CREATE TABLE TIPO_CLIENTE (
	TIPO_ID smallint NOT NULL,
	TIPO_DESCRIPCION varchar(40),
	CONSTRAINT TIPO_CLIENTE_pk PRIMARY KEY (TIPO_ID)
);

CREATE TABLE RUTINA (
	RUTI_CODE smallint NOT NULL,
	RUTI_NOM varchar(20),
	RUTI_DETA varchar(100),
	CONSTRAINT RUTINA_pk PRIMARY KEY (RUTI_CODE)
);

CREATE TABLE TIPO_PLAN (
	PLAN_ID integer NOT NULL,
	PLAN_NOMBRE varchar(40),
	PLN_DETALLE varchar(40),
	PLAN_COSTO float,
	CONSTRAINT TIPO_PLAN_pk PRIMARY KEY (PLAN_ID)
);

CREATE TABLE SECCION (
	SEC_CODI integer NOT NULL,
	SEC_NOM varchar(50),
	SEC_TIPO varchar(40),
	CONSTRAINT SECCION_pk PRIMARY KEY (SEC_CODI)
);

CREATE TABLE FACTURA (
	FACT_NUM varchar(10) NOT NULL,
	FACT_FECH date,
	FACT_SUBTO float,
	FACT_TOTAL float,
	PER_CODE_PERSONAL integer NOT NULL,
	CONSTRAINT FACTURA_pk PRIMARY KEY (FACT_NUM)
);

CREATE TABLE PRODUCTO_ADICIONAL (
	PRO_ADI_COD integer NOT NULL,
	PRO_ADI_NOMBRE varchar(40),
	PRO_ADI_DESCR varchar(40),
	PRO_ADI_COSTO float,
	CONSTRAINT PRODUCTO_ADICIONAL_pk PRIMARY KEY (PRO_ADI_COD)
);

CREATE TABLE EMPRESA_DE_MANTENIMIENTO (
	EMPRESA_COD smallint NOT NULL,
	EMPRESA_NOMBRE varchar(40),
	EMPRESA_CELULAR varchar(40),
	EMPRESA_DIRECCIO varchar(40),
	EMPRESA_CORREO varchar(40),
	EMPRESA_REPRESENTANTE varchar(40),
	CONSTRAINT EMPRESA_DE_MANTENIMIENTO_pk PRIMARY KEY (EMPRESA_COD)
);

CREATE TABLE INGRESO_GIMNASIO (
	GIM_ID smallint NOT NULL,
	GIM_INGRESO timestamp,
	GIM_SALIDA timestamp,
	CLI_CED_CLIENTE integer NOT NULL,
	PLAN_ID_TIPO_PLAN integer NOT NULL,
	SEC_CODI_SECCION integer NOT NULL,
	CONSTRAINT INGRESO_GIMNASIO_pk PRIMARY KEY (GIM_ID)
);

CREATE TABLE DETALLE_FACTURA (
	DETA_ID smallint NOT NULL,
	DETA_CANT integer NOT NULL,
	CLI_CED_CLIENTE integer NOT NULL,
	PRO_ADI_COD_PRODUCTO_ADICIONAL integer NOT NULL,
	FACT_NUM_FACTURA varchar(10) NOT NULL,
	CONSTRAINT DETALLE_FACTURA_pk PRIMARY KEY (DETA_ID)
);

CREATE TABLE USO_MAQUINA (
	USO_ID smallint NOT NULL,
	MAQ_COD_MAQUINA smallint NOT NULL,
	CLI_CED_CLIENTE integer NOT NULL,
	CONSTRAINT USO_MAQUINA_pk PRIMARY KEY (USO_ID)
);

CREATE TABLE RUTINA_ESTABLECIDA (
	RUTI_ID smallint NOT NULL,
	RUTI_FECHA date NOT NULL,
	RUTI_CODE_RUTINA smallint NOT NULL,
	PER_CODE_PERSONAL integer NOT NULL,
	CONSTRAINT RUTINA_ESTABLECIDA_pk PRIMARY KEY (RUTI_ID)
);